### PR TITLE
Trigger monitor

### PR DESCRIPTION
**Pull request by ggggggggg**
very basic trigger monitor living in the observe tab, you could wait to merge, or merge now if you really want something to see triggers with right away, or just checkout this branch

### CODE REVIEW

**Comment by ggggggggg** [comment]
I think this is ready to pull, you should probably give it one quick test.

It uses QPushButtons to represent each channel, and right now only supports a simple row column layout. It should be fairly straightforward to modify to support maps.  The buttons could be used to disable or enable channels, so I made them checkable to indicate they've been pressed, though it does nothing right now.

**Comment by joefowler** [comment]
Hey, connect to 687raven and see what you make of it. That computer is running 8x30 (240 error + 240 FB channels). Triggers on both types of channel are auto trigger every 250 ms. I will leave it running that way for a while.

Your labels (meaning tool tips) and geometry for the buttons (?) seem laid out incorrectly somehow. Maybe we should discuss how to use the channel name message?

Also, why are the buttons "checkable"? I think they shouldn't be.

**Comment by ggggggggg** [comment]
The buttons are checkable because the previous use case was to turn on or off streams, and you keep talking about wanting that feature. So I thought having them checkable would make that information obvious.

**Comment by joefowler** [comment]
Ah, okay. So maybe we make them uncheckable for now, given that they don't do anything?

**Comment by ggggggggg** [comment]
I fixed the row/column naming, and added a channel number. The row/column naming only applies to the grid right now, not the rows/columns of the lancero, because I'm not handling err/fb. Was hoping using the channel names would clarify this.

I tried to use the channel names, but it doesn't work. Must have misunderstood part of it.

**Comment by ggggggggg** [comment]
I think the variation in count rate with auto triggers is real. See the output of this script:

```python
import zmq
import numpy as np
import time
from collections import OrderedDict, deque
PORT = 5504

ctx = zmq.Context() # context is required to create zmq socket
socket = zmq.Socket(ctx, zmq.SUB) # make a subscriber socket
socket.connect ("tcp://687raven:%s" % PORT) # connect to the server
socket.set_hwm(10000) # set the recieve side message buffer limit
socket.setsockopt(zmq.SUBSCRIBE, "") # subscribe to all message, since all start with ""

dtype_header=np.dtype([("chan",np.uint16),("header version",np.uint8),
     ("npresamples",np.uint32),("nsamples",np.uint32),("pretrig_mean","f4"),("peak_value","f4"),
     ("pulse_rms","f4"),("pulse_average","f4"),("residualStdDev","f4"),
     ("unixnano",np.uint64), ("trig frame",np.uint64)])



def add_counts(counts):
    while True:
        # read all available message, return when none are availble
        try:
            m = socket.recv_multipart(flags=zmq.NOBLOCK)
            header = np.frombuffer(m[0],dtype_header)[0]
            chan = header["chan"]
            unixnano = header["unixnano"]
            d = counts.get(chan,deque())
            d.append(int(unixnano))
            counts[chan]=d
        except zmq.ZMQError:
            break
    return counts

def nowNano():
    return int(round(time.time()*1e9))

def clearBefore(d, t0nano):
    removed = 0
    while len(d)>0:
        t = v.pop()
        if d>t0nano:
            d.appendleft(t)
            break
        removed+=1
    return removed



counts = OrderedDict()
tloNano = int(np.ceil(time.time())*1e9)
thiNano = tloNano+1000000000
thiPlusBuffer = thiNano*1e-9+0.05 # 50 ms buffer
tstart = time.time()
lastcount = 0
while True:
    add_counts(counts)
    time.sleep(1)
    if len(counts)>0:
        d=counts[0]
        print("elapsed {:.2f} s, framcecounts {}\n".format(time.time()-tstart,d))
        while len(d) > 0:
            count = d.popleft()
            print("time difference between triggers {:.2f} s, framecount={}, last_framecount={}".format((count-lastcount)*1e-9, count, lastcount) )
            lastcount = count


# n=clearBefore(counts[0],t0nano)
```

**Comment by joefowler** [comment]
You're saying that the auto trigger is not functioning properly? Or perhaps the time-stamper isn't?

Seems like we should check the frame counts to see that auto triggers are always the expected distance apart in frames.

**Comment by ggggggggg** [comment]
Thats what the script I just posted does.

Yes it appears auto trigger is not working correctly.

**Comment by joefowler** [comment]
No, your script looks at the timestamp and calls it a "frame count" in the printed messages. I mean actually look at the frame count. It would mean looking at the header item `trig frame` rather than `unixnano`.

**Pull request merged**
